### ISSUE TITLE
[SIDECAR] sidecar servers should have an "enabled" switch

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-sidecar#255]
All the servers inside sidecar:
* Admin api server
* Sse server
* REST API server
* RPC server
should, in their respective configuration have a `enable_server` property which defaults to `false` (analogously as in the node configurations). If `enable_server` is false - the server doesn't spin up. If all servers are defined in config but have `enable_server= false`, sidecar should exit.

**Comment by devendran-m** [comment]
As per the triage, @zajko will check and confirm if this is already done.

**Comment by devendran-m** [comment]
Confirmed as done.
