### ISSUE TITLE
Include chainspec, config and accounts TOML resources when publishing the Execution Engine testing test support crate.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-sidecar#285]
Genesis requests exported by the testing crate require the presence of a sample chainspec. We need to include this chainspec when publishing the test support crate.

**Comment by jacek-casper** [comment]
We've identified the issue to be the fact that the local chainspec is a symlink which points to a gitignored file which is generated during the node build with make. The file is not present when the test-support crate is built as a cargo dependency alone. We intend to fix it by packaging `chainspec.toml.in` with the test support crate and adding a small step in its build script that will generate the local chainspec automatically during a cargo build.

@deuszex @alsrdn
