### ISSUE TITLE
Bug report: Transaction rejection error messages in sidecar.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-sidecar#286]
The error messages in the sidecar related to the rejection of transaction from the node implies that execution of invalid transactions is being attempted, and failing. These should be reworked, in conjunction with changes to the error messages reported over the binary to facilitate more ergonomic use.

**Comment by zacshowa** [comment]
This PR is finished and merged [here](https://github.com/casper-network/casper-sidecar/pull/307)
