### ISSUE TITLE
[SIDECAR] missing fields in config should have a more descriptive error message

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-sidecar#331]
When a mandatory field is missing either from the root of the config toml or from any of the nested sub-structures we should get an informative error that is easy to comprehend

**Comment by wojcik91** [comment]
Current TOML parsing errors seem to be good enough - pointing out a specific line and config field.

I added more strict typing in https://github.com/casper-network/casper-sidecar/pull/353 to catch more errors during parsing.

**Comment by wojcik91** [comment]
Will also put up another PR to make address & port config for all connections more consistent (i.e. always specify IP and port separately).

**Comment by devendran-m** [comment]
Per @wojcik91's update today, he is finishing up refactoring IP & port configs.
