### ISSUE TITLE
[SIDECAR] Sidecar should react to linux signals

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-sidecar#333]
When the OS is sending a shutdown signal to Sidecar, the app should gracefully shutdown. The most important feature here is that the sse server should store the last message id index value and be able to use it on next spinup

**Comment by devendran-m** [comment]
As per the triage, it's valid but not high priority.

**Comment by devendran-m** [comment]
A nice-to-have feature, i.e. to stop the sidecar gracefully.
