### ISSUE TITLE
[SIDECAR] determine how the API behaves when fetching different entities that get migrated in 2.0

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-sidecar#346]
We need to determine how some of the API endpoints behave fetching data through the 2.0 boundary. The data scenarios are:
1. Account that was created in 1.x but not updated in 2.0
2. Account that was created in 1.x and updated in 2.0
3. Account that was created in 2.0
4. Package that was created in 1.x but not updated in 2.0
5. Package that was created in 1.x and updated in 2.0
6. Package that was created in 2.0
 
Ways to access data:
* Fetch `state_get_item` for account/contract
* "state_get_account_info"
* "state_get_entity"
* "state_get_package"
* "query_global_state" (?)

**Comment by devendran-m** [comment]
As per @zajko ;

> I'm blocked on the [API discovery ticket](https://github.com/casper-network/casper-sidecar/issues/346) by the bug Karan is working on (or at least is aware of - the one that prevents the node to upgrade from 1.x to 2.x with addressable entities enabled).

**Comment by zajko** [comment]
My general findings:
- Regarding accounts
  - JSON RPC API "state_get_account_info" returns "Account" entity for non-migrated accounts. It returns "Account migrated to an addressable entity" error for migrated account. This is inconsistent with how "state_get_item" works, we might want to reconsider that.
  - JSON RPC API "state_get_item" with Key::Account (which is BinaryRequest::Get(GetRequest::State(GlobalStateRequest(Item(Key::Account))))) returns  Account for not migrated and a pointer to the addressable entity for migrated:
  
```
  {
    "jsonrpc": "2.0",
    "id": 124,
    "result": {
        "api_version": "2.0.0",
        "stored_value": {
            "CLValue": {
                "cl_type": "Key",
                "bytes": "1101df2cbf6601a1243bcbad13499d6f813e6eab23fc5b63e19eb428757675b13cbc",
                "parsed": "entity-account-df2cbf6601a1243bcbad13499d6f813e6eab23fc5b63e19eb428757675b13cbc"
            }
        },
        "merkle_proof": "<redacted>"
    }
  }
```

  - JSON RPC API "state_get_item" with Key::AddressableEntity(EntityAddress::Account) returns nothing for 1.x accounts, and AddressableEntity for migrated (which is expected)
    - state_get_entity for "entity_identifier": {"AccountHash":"account-hash-*"} returns Account when account is not migrated
    - state_get_entity for "entity_identifier": {"AccountHash":"account-hash-*"} returns AddressableEntity when account is migrated
  - "query_global_state" returns Account for not migrated and a Stored value "reference" to addressable antity for migrated (as for "state_get_item" with Key::Account

- Regarding contracts
  - "query_global_state" with hash of contract returns Contract entity for non-migrated BUT the structure differs slightly fomr the response of v1 - in v1 the entry point structure was flattened:
  v1 response:
  ```
     "entry_points": [
          {
            "name": "counter_get",
            "args": [],
            "ret": "I32",
            "access": "Public",
            "entry_point_type": "Contract"
          },
      (...)
  ```
   v2 response:
   ```
        "entry_points": [
                    {
                        "name": "counter_get",
                        "entry_point": {
                            "name": "counter_get",
                            "args": [],
                            "ret": "I32",
                            "access": "Public",
                            "entry_point_type": "Called"
                        }
              },
         (...)
   ```

- Bugs and eyebrowraisers that I found
   - (eyebrowraiser/bug(?)) I couldn't figure a way to migrate a contract. Is that event possible? Trying to call an entrypoint of a contract created in v1 results in a "The deploy was invalid: no such entry point" error
   - (bug) When trying to deploy a session wasm on an account that was created in 1.x I get a runtime exception. This does not happen if I just start a 2.0 node that runs with 2.0 created users. The error: "Unexpected variant of a stored value"
   - (eyebrowraiser) `state_get_item` for entity_account returns the AddressableEntity without the named keys. On the other hand, `state_get_entity` (either using “acocunt-hash-*” or “entity-account-*” keys yiela AddressableEntity with named keys
