### ISSUE TITLE
Sidecar misses BlockAdded messages

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-sidecar#348]
In a scenario where the node emits a lot of data, sidecar seems to miss BlockAdded events, here is the information provided by @thamps-casp :

> The latest fix to client allows the CEP78 contract to be installed (with --install-upgrade flag only) and mint transactions are allocated to Lane 4.
There is another bug likely within the sidecar - eventstream - observing missed or unemitted events on sidecar
During a large deploy
ex. casper-node:9999/events - I am able to capture events for 'BlockAdded' and others
in sidecar:19999 - the 'BlockAdded' events are being missed and only 'TransactionAccepted' and 'FinalitySignature' is being found.
This does not happen when less load on network or node. (the solid color on graph represents no block event was received) (edited) 
<img width="1109" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07b3ffaf63e14f151513de32652b3096711cad57/image.png" alt="image.png" />
> Nodes SSE is correctly emitting all the everts

**Comment by thamps** [comment]
casper-node: feat-2.0: `1305f65716b687bac362d9747cbe2d521f96007f`
casper-sidecar: `45526666badab0472feffb418edd85f657408e12`

I am unable to re-produce this error anymore. Can close this for now.

Network: 5 + 2 (8s)
Test:
- deploy native transfers
- deploy cep18 transfers and mints in waves.

At a single point upto 40,000 deploys in buffer. The sidecar continued to emit the BlockAdded events and captured by both prometheus and see exporter.

![image](https://github.com/user-attachments/assets/9bdc0f4d-ba39-4f88-a7dd-b2aab37013dc)
