### ISSUE TITLE
[BUG] `casper-sidecar` crashed with an error after the native `redelegate` command

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-sidecar#371]
Bug reported by @Jiuhong-casperlabs

Issue: `casper-sidecar` crashed due to an error after the native `redelegate` command.

Native `redelegate` command;
```bash
casper-client put-transaction redelegate \
--chain-name casper-jiuhong-test-jh \
--delegator 014df7e27747b916ad006b2e7acf750536d080e92a7aeef4062db8724b3d2b422d \
--validator 0141247b3eb4244918d14d3d6df84e01e7a46f90287739ac6e131b4f9fb3677f34 \
--new-validator 01ca732617ff8c51e3a415aa426a1fcc8531ae98b2f70a92e704c486372bde21d8 \
--transaction-amount 500000000000 \
--gas-price-tolerance 1 \
--pricing-mode fixed \
--secret-key /etc/casper/faucet/secret_key.pem
```

Error:
```bash
2024-11-28T07:56:00.082500Z  WARN casper_event_listener: Lost connection to node 127.0.0.1, on attempt 6/100
2024-11-28T07:56:10.104829Z ERROR casper_event_listener::connection_manager: ; error_message="Serde Error: Couldn't deserialize Error when deserializing SSE event from node: bid-addr-key from string error: invalid tag at line 1 column 1435"
2024-11-28T07:56:10.104916Z ERROR casper_event_listener: Error on start_handling: NonRecoverableError: Serde Error: Couldn't deserialize Error when deserializing SSE event from node: bid-addr-key from string error: invalid tag at line 1 column 1435
2024-11-28T07:56:10.104933Z ERROR casper_event_listener: Restarting event listener 127.0.0.1:9999 because of NonRecoverableError: Serde Error: Couldn't deserialize Error when deserializing SSE event from node: bid-addr-key from string error: invalid tag at line 1 column 1435
2024-11-28T07:56:10.104944Z  WARN casper_event_listener: Lost connection to node 127.0.0.1, on attempt 7/100
```

**Comment by devendran-m** [comment]
Hi @Jiuhong-casperlabs 

Based on the sprint entry discussion yesterday. The changes introduced via casper-node PR https://github.com/casper-network/casper-node/pull/4987 is expected to resolve this bug. Therefore we would like your help in the following in the current sprint - Dec 3 - 17;

- Please retest the following bugs and confirm if they are fixed?
- Investigate if any other operations (e.g., delegate, re-delegate) may have the same underlying issue.? - If yes, a separate bug ticket will be created for RCA and closure.

Retest required;
https://github.com/casper-network/casper-sidecar/issues/370
https://github.com/casper-network/casper-sidecar/issues/371

**Comment by Jiu-hong** [comment]
The original issue was fixed but a new strange thing happened:
The new validator-delegator bid (bid-addr-02<new validator accountHash><delegator accountHash>) cannot be found from global-state

command:
```
casper-client put-transaction redelegate \
--chain-name casper-test-jh \
--delegator 0184a1a8ae32bdb1d3abcecb989c33e75c8f0203bf1e7f08522c85899c99a89785 \
--validator 01d75e075dd3e59cbd6a7cdec68d61fd9c9859736edb21f415ccada6bdc3142ed5 \
--new-validator 012d323a5e4c7b10d80fcbd5fadfb82d9781127b37c85006f0827e961c350cec1f \
--transaction-amount 500000000000 \
--gas-price-tolerance 1 \
--pricing-mode fixed \
--secret-key /etc/casper/faucet/secret_key.pem
```
delegator:
account-hash-aac33e71b83d537743c9be31759e2458b388bcaff9a0222056becd24d1aa668c
new validator:
account-hash-8e10016776249bf6f940307f85051d99ce721c59aa15f32d5364becd27a7f214

new validator-delegator pairs cannot be found from global-state
```
{
  "id": -573285493134384228,
  "jsonrpc": "2.0",
  "method": "query_global_state",
  "params": {
      "key": "bid-addr-028e10016776249bf6f940307f85051d99ce721c59aa15f32d5364becd27a7f214aac33e71b83d537743c9be31759e2458b388bcaff9a0222056becd24d1aa668c"
  }
}
=>
{
    "jsonrpc": "2.0",
    "id": -573285493134384228,
    "error": {
        "code": -32003,
        "message": "Query failed",
        "data": "value was not found in the global state"
    }
}
```

**Comment by devendran-m** [comment]
Thank you very much, @Jiuhong-casperlabs 
I will create a separate bug ticket for the new issue that you have encountered and reported.  As the original bug is resolved, I will close this ticket.
