### ISSUE TITLE
[BUG] Instead of unbonding part of the total stake, the whole stake was unbonded 

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-sidecar#377]
This is a bug identified when retesting another bug #370. Reported by @Jiuhong-casperlabs 

Instead of unbonding part of the total stake, the whole stake was unbonded and the state switched from validate to keepup from the next era.

command:

```
casper-client put-transaction withdraw-bid \
--public-key 015c6f2f6cedc2cbb182e0df3dfa7c435bba692c3e0381521a45c0538a61c5998b \
--transaction-amount 935543258758 \
--chain-name casper-test-jh \
--gas-price-tolerance 1 \
--pricing-mode fixed \
--secret-key /etc/casper/validator_keys/secret_key.pem
```
**before:** staked amount: 80935543258758
**after:**
. bid(bid-addr-01accounthash) cannot be found from global state
. validate -> keepup at the next era

**Comment by Jiu-hong** [comment]
This isn't an issue but works as design.
The rest stake is less than the minimum_bid_amount defined in the chainspec so is treated as a full unbond of a validator.

**Comment by devendran-m** [comment]
Thanks, @Jiuhong-casperlabs , for the updates.

**Comment by devendran-m** [comment]
This is not a bug. Works as per design, therefore closed.
