### ISSUE TITLE
[SSE Sidecar] GraphQL Analysis

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-sidecar#69]
@hectoratcasper commented on [Thu Jun 02 2022](https://github.com/CasperLabs/product/issues/186)

# Identify required elements to support future implementations for GraphQL

# Expected result
GraphQL Analysis determining the following:
Re usage of RESTful models o new design enhancements.
Subscribe to various chunks of server data
Request multiple objects
Maintain constant connection with server using Websockets (bi - direccional) 

# Resources
Please refer to the SSE Sidecar High Level Design document for high level implementation details.

https://docs.google.com/document/d/1vBRbBmij9HHotY_8HIaUKk5a9Kq9Rqgxlk-UAE_F7xs/edit

Repository for this project: 
https://github.com/CasperLabs/event-sidecar

**Comment by devendran-m** [comment]
As per the triage with Jakub, the business case for this requirement is not clear. Therefore, advised to close this and revisit in the future should GraphQL is required. On that basis, closing this ticket.
