### ISSUE TITLE
[SSE Sidecar] Create switch block filtering

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-sidecar#71]
Step events indicate a switch block has been processed, which in turn, indicates the end of an era.   Allow the application of a filter to pass through or exclude step events from the sidecar endpoint. 

@devendran-m commented on [Tue Aug 16 2022](https://github.com/CasperLabs/product/issues/268)

Create switch block filtering

---

@caspersteve commented on [Sun Oct 30 2022](https://github.com/CasperLabs/product/issues/268#issuecomment-1296369745)

Related to Checkpointing v1.0 and Explorer v1.1

**Comment by devendran-m** [comment]
Hi @sacherjj , do you know if this repo still exists please? 
- https://github.com/CasperLabs/product/

**Comment by devendran-m** [comment]
Jakub's recommendation is to close this as the details on this ticket are insufficient. Should this filter is required, then a new request with detailed specification is necessary.

**Comment by devendran-m** [comment]
Closing based on @zajko 's recommendations.
