### ISSUE TITLE
[SSE Sidecar] Add Basic authentication to RESTful API

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-sidecar#72]
@hectoratcasper commented on [Thu Jun 02 2022](https://github.com/CasperLabs/product/issues/181)

# Add Basic authentication to RESTful API

The sidecar exposes blockchain event endpoints through a RESTful API, but authentication is not implemented for the MVP version. In order to restrict access to these endpoints, we need to implement basic authentication using an API key as the credential.

The RESTful endpoint should support basic authentication using an API key.

```
curl --header "api_key: SIDECAR_API_KEY" http://127.0.0.1:18888/block
```

The sidecar should be able to work in both authenticated and non-authenticated modes.

New settings can be added to the existing configuration file in a new [auth] section: 

```
# TOML configuration file for Rust sidecar project 

[auth]
enabled = true

[auth.users] 
username = "user1"
api_key = "SIDECAR_API_KEY" 
```

**api_key**: The value of the API key to use for authentication.  If this value is not provided or is empty, authentication will be disabled.

**enabled**: A boolean value indicating whether authentication should be enabled. If set to false, the server will not require authentication and requests will be processed without checking for an API key. If set to true, the server will require an API key in order to process requests.

# Resources
Please refer to the SSE Sidecar High Level Design document for high level implementation details.

https://docs.google.com/document/d/1vBRbBmij9HHotY_8HIaUKk5a9Kq9Rqgxlk-UAE_F7xs/edit#heading=h.95i1qjit3j6q

Repository for this project: 
https://github.com/CasperLabs/event-sidecar

**Comment by devendran-m** [comment]
Based on the triage with Jakub, the following questions are open and need answers before working on this;
1. Business requirements clarity and urgency.

If we were to do this, we need sibling tickets to add authentication for SSE and RPC as well.

**Comment by devendran-m** [comment]
Closing as no business urgency or rationale elaborated.
